language: cpp

os: osx
osx_image: xcode11

script:
  - "./abuild"
  
before_deploy:
  - git config --local user.name $GIT_USER
  - git config --local user.email $GIT_EMAIL
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  name: Clover_v2.5k_r$TRAVIS_TAG
  body: $TRAVIS_COMMIT_MESSAGE
  file_glob: true
  file:
    - Build/CloverPackage/sym/Clover_v2.5k_r*
    - Build/CloverPackage/sym/*.lzma
  skip_cleanup: true
  on:
    Branch: master
