language: cpp

os: osx
osx_image: xcode11.2


script:
  - "./abuild"
  
before_deploy:
  - git config --local user.name $GIT_USER
  - git config --local user.email $GIT_EMAIL
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(cat "$TRAVIS_BUILD_DIR/Build/TAG")}
  - export LAST_COMMIT_MESSAGE=$(cat "$TRAVIS_BUILD_DIR/Build/MESSAGE")
  - export PRE_RELEASE=$(cat "$TRAVIS_BUILD_DIR/Build/PRERELEASE")
  - git remote rm origin
  - git remote add origin https://n-d-k:$GITHUB_TOKEN@github.com/n-d-k/ndk_tools.git
  - git commit --allow-empty -m "Auto Travis"
  - git push origin master
  - git tag $TRAVIS_TAG || exit 0
  
deploy:
  provider: releases
  edge: true
  allow_failure: true
  api_key: $GITHUB_TOKEN
  name: Clover_v2.5k_r$TRAVIS_TAG
  body: $LAST_COMMIT_MESSAGE
  prerelease: $PRE_RELEASE
  file_glob: true
  file:
    - Build/CloverPackage/sym/Clover_v2.5k_r*
    - Build/CloverPackage/sym/*.lzma
  on:
    Branch: master
